cart/urls.py
from django.conf.urls import url
from .views import add_to_cart,cart_list,item_delete
urlpatterns = [
    
	url(r'^$',        cart_list, name='list'),
	url(r'^add/$', add_to_cart, name='add'),
	# url(r'^(?P<id>\d+)/$', product_detail, name='detail'),
	# url(r'^(?P<id>\d+)/edit/$', product_update,name='update'),
	url(r'^item/(?P<id>\d+)/delete/$', item_delete, name='delete-item'),

]

orders/urls.py
from django.conf.urls import url
from .views import make_order,order_detail,order_list
urlpatterns = [
    
	url(r'^$',      order_list, name='list'),
	url(r'^(?P<id>\d+)/$', order_detail, name='detail'),
	url(r'^submit/$',      make_order, name='submit'),
]

products/urls.py
from django.conf.urls import url
from .views import (product_update,product_list,product_detail,product_delete,product_create)
urlpatterns = [
    
	url(r'^$',        product_list, name='list'),
	url(r'^create/$', product_create, name='create'),
	url(r'^(?P<id>\d+)/$', product_detail, name='detail'),
	url(r'^(?P<id>\d+)/edit/$', product_update,name='update'),
	url(r'^(?P<id>\d+)/delete/$', product_delete, name='delete'),

]

shop/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from accounts.views import (login_view, register_view,logout_view,register_staff)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^reviews/', include("reviews.urls",namespace='reviews')),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^register/', register_view, name='register'),
    url(r'^register-staff/', register_staff, name='staff'),

    url(r'^', include("products.urls",namespace='product')),
    url(r'^cart/', include("cart.urls",namespace='cart')),
    url(r'^order/', include("orders.urls",namespace='order')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/models.py
from __future__ import unicode_literals
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse
# from reviews.models import Review

# Create your models here.

def default_image():
	return "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg"

class Product(models.Model):
	admin = models.ForeignKey(settings.AUTH_USER_MODEL,limit_choices_to={'is_staff': True},default=1)
	name = models.CharField(max_length=120)
	seller = models.CharField(max_length=120)
	category = models.CharField(max_length=120)
	description = models.TextField()
	price = models.FloatField()
	stock = models.IntegerField(default=1)
	image = models.CharField(max_length=800,blank=True,default=default_image())
	
	timestamp = models.DateTimeField(auto_now=False,auto_now_add=True)
	updated = models.DateTimeField(auto_now=True,auto_now_add=False)


	def __unicode__(self):
		return self.name

	def get_absolute_url(self):
		return reverse("product:detail", kwargs={"id":self.id})	

	def get_delete_url(self):
		return reverse("product:delete", kwargs={"id":self.id})			

products/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):

	class Meta:
		model = Product
		fields = [ "name", "category", "seller","price","stock","image","description"]

products/views.py
from django.shortcuts import render

from django.shortcuts import render , get_object_or_404, redirect
from django.http import HttpResponse,HttpResponseRedirect,Http404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q ,Avg,Count

from reviews.forms import ReviewForm
from reviews.models import Review
from .forms import ProductForm
from .models import Product

# Create your views here.
@login_required
def product_create(request):
	if not request.user.is_staff:
		raise Http404	
	title = "Create"
	form = ProductForm(request.POST or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.admin = request.user
		instance.save()
		messages.success(request, "Successfuly Created")
		return HttpResponseRedirect(instance.get_absolute_url())
	
	context ={"form": form,"title":title}
	return render(request,"product_form.html",context)

@login_required
def product_update(request,id):
	if not request.user.is_staff:
		raise Http404
	title = "Update"	
	instance = get_object_or_404(Product,id=id)		
	form = ProductForm(request.POST or None,instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		messages.success(request, "Successfuly Updated")
		return HttpResponseRedirect(instance.get_absolute_url())
	
	context ={"form": form,"title":title}
	return render(request,"product_form.html",context)	

def product_list(request):
	queryset_list = Product.objects.all()
	query = request.GET.get('q')
	if query:
		queryset_list= queryset_list.filter(
			Q(name__icontains=query) |
			Q(description__icontains=query) |
			Q(seller__icontains=query) |
			Q(category__icontains=query)
			).distinct()
	paginator = Paginator(queryset_list, 10) # Show 3 posts per page
	page_request_var = 'page'
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)

	context = {
		"title":"products",
		"object_list" :queryset,
		"page_request_var":page_request_var,
	}
	return render(request,"product_list.html",context)


def product_detail(request,id):
	product = get_object_or_404(Product,id=id)
	reviews = Review.objects.all().filter(product=product)	
	average_rating = reviews.aggregate(Avg('rating'))
	if average_rating['rating__avg']:
		average_rating = int(round(average_rating['rating__avg']))
	else:
		average_rating = 0
	reviews_count = reviews.aggregate(Count('id'))
	reviews_count = reviews_count['id__count']
	
	form = ReviewForm(request.POST or None)
	if form.is_valid() and request.user.is_authenticated():
		review = form.save(commit=False)
		review.user = request.user 
		review.product = product
		review.save()
		return HttpResponseRedirect(product.get_absolute_url())

	context = {
	"title":product.name,
	"instance":product,
	"review_form":form,
	"reviews":reviews,
	"average_rating":average_rating,
	"reviews_count":reviews_count

	}
	return render(request,"product_detail.html",context)

@login_required
def product_delete(request,id):
	obj = get_object_or_404(Product,id=id)
	
	if not request.user.is_staff: #or (obj.admin != request.user)
		messages.success(request,"you do not have permission to this action")
		return HttpResponseRedirect(obj.get_absolute_url())

	if request.method == "POST":
		obj.delete()
		messages.success(request,"Product has been deleted")
		return HttpResponseRedirect("/")

	else:
		messages.error(request,"the request must be POST")
		return HttpResponseRedirect("/")
	
	

templates/base.html
{%load staticfiles%}
<!DOCTYPE html>
<html>
<head>
	<title>{%block head_title%}E-shop{%endblock%}</title>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
	<!-- Font awesome cdn -->
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css"
	 href='{% static "css/base.css" %}'>
	
</head>
<body>

<!-- ////////////// -->
{%include "messages_display.html"%}
<div class="container">
	<ol class="breadcrumb">
		<li><a href="{%url 'product:list' %}">Home</a></li>
		{%block product_detail%}
		{%endblock%}
		{%block product_list%}
		{%endblock%}
		{%if not request.user.is_authenticated%}
		<li class="pull-right"><a href="{%url 'register'%}">Register</a></li>			
		<li class="pull-right"><a href="{%url 'login'%}">Login</a></li>
		<li class="pull-right"><a href="{%url 'staff'%}">Staff</a></li>
		{%else%}	
		<li class="pull-right"><a href="{%url 'logout'%}">Logout</a></li> 
		{%if not request.user.is_staff%}
		<li class="pull-right"><a href="{%url 'cart:list'%}"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span></a></li> 
		{%endif%}
		<li class="pull-right"><a href="{%url 'order:list'%}"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> {{request.user.username}}</a></li>
		{%endif%}
	</ol>
{%block content%}	
{%endblock%}
</div>

<script
  src="https://code.jquery.com/jquery-1.12.4.min.js"
  integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
  crossorigin="anonymous"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script type="text/javascript">
	$(document).ready(function(){
	
		/*$(".product-detail-item img").each(function(){
			$(this).addClass("img-responsive")		
		})
	*/
		

	})
</script>
</body>
</html>

templates/cart_list.html
{%extends "base.html"%}

{%block head_title%}{{title}} | {{block.super}}{%endblock%}


{%block content%}
{% if not object_list.exists %}	
<h1>Your Cart is Currently empty</h1>
{%else%}
<div class="col-sm-12 col-sm-offset-3">
  <h3>Total Price {{total_price}} $</h3>
</div>

<div class="row">

{% for cart_item in object_list %}
  <div class="col-sm-6 col-md-2">
  
    <div class="thumbnail">
      <img src="{{cart_item.product.image}}" class="img-responsive">
      <div class="caption">
        <h3><a href="{{cart_item.product.get_absolute_url}}">{{cart_item.product.name}}</a></h3>
        <h4> Quantity:{{cart_item.quantity}}</h4>
        <h4>{{cart_item.price}} $</h4>
        <p><a href="{{cart_item.product.get_absolute_url}}" class="btn btn-primary" role="button">View</a> <a href="{%url 'cart:delete-item' cart_item.id %}" class="btn btn-danger pull-right" role="button"><span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span></a></p>
      </div>
    </div>
  </div>
   {%endfor%}
</div>
<br>
<a href="{%url 'order:submit' %}" class="btn btn-success" role="button">Buy Now</a>
<br>
<br>
{%endif%}




{%endblock%}

templates/confirm_delete.html
{%extends "base.html"%}

{%block head_title%}{{title}} | {{block.super}}{%endblock%}
{%block content%}	
<div class="col-sm-6 col-sm-offset-3">
<h1>Confirm Delete</h1>
					<form method="POST" action="">{%csrf_token%}
						<p>are you sure you want to delete: "{{object.content}}"</p>
						<input type="submit" value="Confirm" class="btn btn-warning">
						<a href="{{parent}}" class="btn btn-default">Cancel</a>
					</form>
				</div>

			
			<hr>
</div>	


{%endblock%}

templates/customer_form.html
{%extends "base.html"%}
{% load crispy_forms_tags %}
 
{%block content%}

<div class="col-sm-6 col-sm-offset-3">
<h1>{{title}}</h1>
<hr>
<form method="POST" action="" enctype="multipart/form-data">
{% csrf_token %}
	{{user_form|crispy}}
	{{profile_form|crispy}}
	<input type="submit" class="btn btn-default" value="{{title}}">
</form>
<br>
</div>
{%endblock%}

templates/login_form.html
{%extends "base.html"%}
{% load crispy_forms_tags %}
 
{%block content%}

<div class="col-sm-6 col-sm-offset-3">
<h1>{{title}}</h1>
<hr>
<form method="POST" action="" enctype="multipart/form-data">
{% csrf_token %}
	{{form|crispy}}
	<input type="submit" class="btn btn-default" value="{{title}}">
</form>
<br>
</div>
{%endblock%}

templates/messages_display.html
{% if messages %}
	<div class="messages">
		<ul class="messages">
		{% for message in messages %}
		<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message}}
		</li>
		{% endfor %}
		</ul>
	</div>
{% endif %}

templates/order_detail.html
{%extends "base.html"%}

{%block head_title%}{{title}} | {{block.super}}{%endblock%}


{%block content%}

<div class="col-sm-12 ">
  <h3>Total Cost {{total_price}} $ |ordered at: {{timestamp}} |Address: {{address}}</h3>
</div>

<div class="row">

{% for item in order_qs %}
  <div class="col-sm-6 col-md-2">
  
    <div class="thumbnail">
      <img src="{{item.product.image}}" class="img-responsive">
      <div class="caption">
        <h3><a href="{{item.product.get_absolute_url}}">{{item.product.name}}</a></h3>
        <h4> Quantity:{{item.quantity}}</h4>
        <h4>{{item.price}} $</h4>
        <p><a href="{{item.product.get_absolute_url}}" class="btn btn-primary" role="button">View</a>
        </p>
      </div>
    </div>
  </div>
   {%endfor%}
</div>


<div class="col-sm-9 col-sm-offset-3">
  <h3>we will contact you at your number: {{phone}} before delivery</h3>
  <br>
</div>



{%endblock%}

templates/order_list.html
{%extends "base.html"%}

{%block head_title%}{{title}} | {{block.super}}{%endblock%}


{%block content%}

<div class="col-sm-12 col-sm-offset-3">
  <h3>Order history</h3>
</div>

{% if orders_qs.exists%}

{% for order in orders_qs %}
<div class="row">

<h3>{{forloop.counter}}- <a href="{{order.get_absolute_url}}">{{order.timestamp}}</a></h3>
  
</div>
{%endfor%}

{%else%}

<h1>You have no order history</h1>

{%endif%}

{%endblock%}

templates/product_detail.html
{%extends "base.html"%}
{% load crispy_forms_tags %}
{% load times %}

{%block head_title%}{{title}} | {{block.super}}{%endblock%}

{%block product_detail %}
<li>{{title}}</li>
{%if user.is_staff%}
<li><a href="{%url 'product:update' instance.id %}">Edit product</a></li>
{%endif%}
{%endblock%}

{%block content%}	
<div class="col-sm-6 col-sm-offset-3">
	<div class="thumbnail">
	
	<img class="detail-size" src="{{instance.image}}">
	<div class="caption">
	<h1>{{title}}</h1>
	<h3><small>Seller: {{instance.seller}} | in {{instance.category}} 
	</small></h3>
	<h4><small>{{instance.timestamp|date}}</small></h4>
	
	<h4>price: {{instance.price}} $</h4>
	<p>
			<form class="form" method="POST" action="{%url 'cart:add' %}">{%csrf_token%}
			  <input type="hidden" name="product_id" value="{{instance.id}}">
			  <div class="form-group form-inline">
			    <label>Quantity</label>
			    <input type="number" name="quantity" style="width: 11%" class="form-control" min="1" max="10" value="1">
			  </div>
			  {%if not user.is_staff%}
			  <button type="submit" class="btn btn-success">Add to Cart <i class="fa fa-shopping-cart fa-lg" aria-hidden="true"></i></button>
			  {%endif%}
			</form>
			
		{%if user.is_staff%}
		<form class="pull-right" method="POST" action="{{instance.get_delete_url}}">{%csrf_token%}
			
			<input type="submit" value="Delete" class="btn btn-danger">
		</form>
		<br>
		{%endif%}
	</p>
		
	</div>
	</div>




	<div class="row">
		<div class="col-sm-12">
			<div>
			<h2>Description</h2>
			{{instance.description}}
			<hr>
			<p>Average rating: {%for s in average_rating|times %}<i class="fa fa-star" aria-hidden="true"></i>{%endfor%}{%for s in average_rating|times2 %}<i class="fa fa-star-o" aria-hidden="true"></i>{%endfor%} out of {{reviews_count}} reviews</p>
			</div>
			
			<hr>
			<br>
			<div>
			<p class="lead">Reviews</p>
			{%if request.user.is_authenticated%}
			<form method="POST" action="">{%csrf_token%}
				{{review_form|crispy}}
				<input type="submit" value="Post" class="btn btn-default">
			</form>
			{%else%}
			<p>you must login to comment</p>
			{%endif%}
			<hr>
			{%for comment in reviews%}
			<blockquote>
			  <p>{%for s in comment.rating|times %}<i class="fa fa-star" aria-hidden="true"></i>{%endfor%}{%for s in comment.rating|times2 %}<i class="fa fa-star-o" aria-hidden="true"></i>{%endfor%} </p>
			  <p>{{comment.content}}</p>
			  <footer>via {{comment.user}} | {{comment.timestamp|timesince}} ago</footer>
			</blockquote>
			<hr>
			{%endfor%}
			</div>
			
	</div>
</div>	
</div>

{%endblock%}

templates/product_form.html
{%extends "base.html"%}
{% load crispy_forms_tags %}
 
{%block head_extra%}{{form.media}}{%endblock%}

{%block content%}

<div class="col-sm-6">
<h1>{{title}} Product</h1>
<hr>
<form method="POST" action="" enctype="multipart/form-data">
{% csrf_token %}
	{{form|crispy}}
	<input type="submit" class="btn btn-default" value="{{title}}">
</form>
<br>
</div>
{%endblock%}

templates/product_list.html
{%extends "base.html"%}

{%block product_list%}
{%if user.is_staff%}
<li><a href="{%url 'product:create' %}">Add new product</a></li>
{%endif%}
{%endblock%}

{%block content%}
<div class="col-sm-6 col-sm-offset-3">
	<h1>{{title}}</h1>
	<form method="GET" action="" class="row">
	<div class="col-sm-6">
		<div class="input-group">
			<input class="form-control" type="text" name="q" placeholder="Search products" value="{{request.GET.q}}">
			<span class="input-group-btn">
				<!-- <input class="btn btn-default" type="submit" value="Search"> -->
				<button class="btn btn-default" type="submit">Search <i class="fa fa-search"></i></button>
			</span>
		</div>
	</div>
	</form>
	<br>
	</div>
	
<div class="row">
{% for product in object_list %}
  <div class="col-sm-6 col-md-4">
  
    <div class="thumbnail">
      <img src="{{product.image}}" class="img-responsive">
      <div class="caption">
        <h3><a href="{{product.get_absolute_url}}">{{product.name}}</a></h3>
        <h4>{{product.price}} $</h4>
        <p><a href="{{product.get_absolute_url}}" class="btn btn-primary" role="button">View</a> <!-- <a href="#" class="btn btn-success pull-right" role="button">+<i class="fa fa-shopping-cart fa-lg" aria-hidden="true"></i></a> --></p>
      </div>
    </div>
  </div>
   {%endfor%}
</div>

	
<div class="col-sm-6 col-sm-offset-3">
<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{page_request_var}}={{ object_list.previous_page_number }}{%if request.GET.q%}&q={{request.GET.q}}{%endif%}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{page_request_var}}={{ object_list.next_page_number }}{%if request.GET.q%}&q={{request.GET.q}}{%endif%}">next</a>
        {% endif %}
    </span>
</div>

</div>

{%endblock%}

templates/staff_form.html
{%extends "base.html"%}
{% load crispy_forms_tags %}
 
{%block content%}

<div class="col-sm-6 col-sm-offset-3">
<h1>{{title}}</h1>
<hr>
<form method="POST" action="" enctype="multipart/form-data">
{% csrf_token %}
	{{form|crispy}}
	<input type="submit" class="btn btn-default" value="{{title}}">
</form>
<br>
</div>
{%endblock%}